---
title: "Assignment 08"
author: "Poisson Regression"
header-includes:
   - \usepackage{xcolor}
   - \definecolor{umn}{RGB}{153, 0, 85}
   - \definecolor{umn2}{rgb}{0.1843137, 0.4509804, 0.5372549}
output: 
  pdf_document:
    highlight: tango
urlcolor: "umn2"
---

This assignment is intended to give you experience working with Poisson regression models to analyze count data. *Do not include any R syntax or output unless it is specifically required in the question.* Please submit your responses to each of the questions below. Please submit your responses to each of the questions below in a printed document. All graphics should be resized so that they do not take up more room than necessary and should have an appropriate caption. All tables should also have an appropriate caption.

This assignment is worth 15 points. Each question is worth 1 point unless otherwise noted. 

\rule{0.5\linewidth}{\linethickness}

For this assignment, you will use the file, *risky-behavior.csv*. This file contains data (provided by Gelman \& Hill, 2007) collected from a randimized trial targeting opposite sex couples at high risk of HIV infection. The intervention provided counseling sessions related to implementing practies that could reduce their likelihood of contracting HIV. Couples were randomized to (1) a control group; (2) a group in which only the female member of the couple participated in the intervention; or (3) a group in which both members of the couple participated in the intervention. These particular data consist of data from 434 individuals who participated in the study. The variables in this file are:

- `female`: Dummy coded sex variable (0=male, 1=female)
- `intervention`: To which level of intervention was the person randomly assigned? (Control group; Both members of the couple received the intervention; Only the female member of the couple received the intervention)
- `hiv_baseline`: Dummy variable indicating whether only the female member of the couple received the intervention (0=no; 1=yes)
- `unprotected_baseline`: Number of unprotected sex acts at baseline
- `unprotected_follow_up`: Number of unprotected sex acts three months after the completion of the study

Gelman, A., \& Hill, J. (2007). *Data analysis using regression and multilevel/hierarchical models*. New York: Cambridge University Press. 

\rule{0.5\linewidth}{\linethickness}


# Effect of Intervention

You will begin the analysis by examining the effect of intervention on the number of unprotected sex acts three months after the completion of the study.

1. Compute and report the number of unprotected sex acts three months after the completion of the study for each of the three levels of intervention.

2. Create a histogram of the number of unprotected sex acts three months after the completion of the study for each of the three levels of intervention.

3. Based on the summary measures and plots, is there

Based on the plot you just created, the relationship between proportion of support and attendance seems linear. Because of this, we can treat the Likert data as continuous; using a line (or polynomial) to fit the relationship. The only caution being that when interpreting a slope, we say something like, "a one-unit difference in $X$ is associated with a $\hat\beta_1$-unit difference in $Y$". For ordinal (Likert) data a one-unit difference in $X$ really indicates a shift from one category to the next highest category.

\pagebreak

2. Fit two logistic models to the data using religious service attendance. In the first model, only include the linear effect of attendance. In the second model, include both a linear and quadratic effect to predict variation in support for same-sex marriage. Which model should be adopted (linear or quadratic)? Justify your response by providing any statistical evidence you used in reaching your decision. (*Note:* The model you adopt here will be henceforth referred to as Model 1.)

<!-- You can see an example of a table of logistic model results in: Raikes, H., Pan, B. A., Luze, G., Tamis-LeMonda, C. S., Brooks-Gunn, J., Constantine, J., Banks Tarullo, L., Raikes, H. A., \& Rodriguez, E. T. (2006). Mother–child bookreading in low-income families: Correlates and outcomes during the first three years of life. *Child Development, 77*(4), 924--953. doi: 10.1111/j.1467-8624.2006.00911.x -->


3. Write the fitted equation for Model 1. (Don't forget to include all appropriate subscripts. Also define any terms in the model that are ambiguous.)

4. Use the fitted equation for Model 1 to predict the (a) log-odds, (b) odds, and (c) probability of someone supporting same-sex marriage if that person attends religious services almost every week.


# Effect of Denomination

5. Are there sample differences in the proportion of people who support same-sex marriage between the denominations? Explain by using evidence from the sample data.

Fit a logistic model to the data using denomination to predict variation in support for same-sex marriage (Model 2). In this model, use Protestant as the reference group.

6. Interpret the effect associated with the `Jewish` coefficient in terms of (a) log-odds, and (b) odds.


# Effect of Attendance and Denomination

Fit the logistic model that includes all the adopted effects for religous service attendance *and* the effects of denomination to predict variation in support of same-sex marriage. (*Note:* This model will be referred to as Model 3.) 

7. Compute and report one of the pseudo-$R^2$ values for Model 3. Also provide an interpretation of this measure.

# Adding Covariates

Now you will examine three potential covariates (`friends`, `age`, and `female`) that have been linked in the substantive literature to support of same-sex marriage. 

8. To help think about which covariates should be included in your model, create a correlation matrix of the outcome, and all three covariates. By referring to this matrix, clearly indicate the order in which you will add covariates into the model.

Fit three logistic models based on the order of importance of the three covariates that also include the effects of religious attendance, and denomination. For example, the first of these three models would include the effects of religious attendance, denomination, and the most important covariate you identifed in Question 8. The second model would include the effects of religious attendance, denomination, and the two most important covariate you identifed. Finally, the third model would include the effects of religious attendance, denomination, and all three covariates.

9. Which of these three models should be adopted as you final model (or set of models)? Justify your response by providing any statistical evidence you used in reaching your decision.

10. Create a table of results from your set of fitted models. This table should include Models 1--3 and also any model(s) you adopted from the previous question. Like other regression tables you have created, be sure to include the estimated coefficients and standard errors for each of the effects included in the models. (To be consistent with ASA recommendations, do not include *p*-values or stars.) Also include the AICc values, and at least one pseudo-$R^2$ value for each model. **(3pts.)**

# Interpreting the Final Model

11. Create a plot that visually displays the results of your final fitted model. Be sure to visually show the effects the focal predictors (religious service attendance and denomination). Also show any pertinent covariates you think are necessary to include. (Think about how the inclusion of the covariates help readers better understand the effects of the focal predictors.)

12. Write a few sentences that tell the data narrative about the effects of religous service attendance and denomination on the support of same-sex marriage. Use the models in your table of model results to help create this narrative. Keep the focus on the focal variables in this narrative. **(2pts.)**





