# Assignments

Below are the due dates for the assignments, as well as links to the RMD and PDF files for each assignment. The due dates may change at the instructor's discretion. Any revised due dates will be announced in class and posted to the website.

<br />


<table class="table">

<thead>
<tr>
<th style="width:50%;">Assignment</th>
<th style="width:15%;">Due Date (T/R)</th>
<th style="width:15%;">Due Date (M/W)</th>
<th style="width:10%;text-align:center">RMD</th>
<th style="width:10%;text-align:center">HTML</th>
</tr>
</thead>

<tbody>

<tr>
<td>Assignment \#1: *Introduction to R Markdown* <br />
  <span style="margin-left:5px; color:#5a067d;font-size:12px;">*[The due date for this assignment is flexible]*</span></td>
<td>Feb. 02</td>
<td>Feb. 03</td>
<td align="center" style="vertical-align:middle;">
[<span class="fab fa-markdown" style="color: #ff2600; font-size: 20px;"></span>](https://github.com/zief0002/epsy-8252/raw/master/assignments/s21-assignment-01-introduction-to-r-markdown.Rmd)
</td>
<td align="center" style="vertical-align:middle;">
[<span class="fa fa-file-pdf" style="color: #ff2600; font-size: 20px;"></span>](https://github.com/zief0002/epsy-8252/raw/master/assignments/s21-assignment-01-introduction-to-r-markdown.pdf)
</td>
</tr>



<tr>
<td>Assignment \#2: *Probability Distributions and xaringan*<br />
  <span style="margin-left:5px; color:#5a067d;font-size:12px;">*[The due date for this assignment is flexible]*</span></td>
<td>Feb. 11</td>
<td>Feb. 15</td>
<td align="center" style="vertical-align:middle;">
[<span class="fab fa-markdown" style="color: #ff2600; font-size: 20px;"></span>](https://github.com/zief0002/epsy-8252/raw/master/assignments/s21-assignment-02-probability-distributions-and-xaringan.Rmd)
</td>
<td align="center" style="vertical-align:middle;">
[<span class="fa fa-file-pdf" style="color: #ff2600; font-size: 20px;"></span>](https://github.com/zief0002/epsy-8252/raw/master/assignments/s21-assignment-02-probability-distributions-and-xaringan.pdf)
</td>
</tr>

<tr>
<td>Assignment \#3: *Polynomial Effects*</td>
<td>Mar. 02</td>
<td>Mar. 03</td>
<td align="center" style="vertical-align:middle;">
[<span class="fab fa-markdown" style="color: #ff2600; font-size: 20px;"></span>](https://github.com/zief0002/epsy-8252/raw/master/assignments/s21-assignment-03-polynomial-effects.Rmd)
</td>
<td align="center" style="vertical-align:middle;">
[<span class="fas fa-link" style="color: #ff2600; font-size: 20px;"></span>](https://zief0002.github.io/epsy-8252/assignments/s21-assignment-03-polynomial-effects.html)
</td>
</tr>

<tr>
<td>Assignment \#4: *Logarithmic Transformations* <span style="margin-left:5px; color:#5a067d;font-size:12px;">*[Updated: 03-01-2021]*</span></td>
<td>Mar. 16</td>
<td>Mar. 17</td>
<td align="center" style="vertical-align:middle;">
[<span class="fab fa-markdown" style="color: #ff2600; font-size: 20px;"></span>](https://github.com/zief0002/epsy-8252/raw/master/assignments/s21-assignment-04-logarithmic-transformations.Rmd)
</td>
<td align="center" style="vertical-align:middle;">
[<span class="fas fa-link" style="color: #ff2600; font-size: 20px;"></span>](https://zief0002.github.io/epsy-8252/assignments/s21-assignment-04-logarithmic-transformations.html)
</td>
</tr>

<tr>
<td>Assignment \#5: *Information Criteria and Model Selection*<span style="margin-left:5px; color:#5a067d;font-size:12px;">*[Updated: 03-10-2021]*</span></td>
<td>Mar. 25</td>
<td>Mar. 29</td>
<td align="center" style="vertical-align:middle;">
[<span class="fab fa-markdown" style="color: #ff2600; font-size: 20px;"></span>](https://github.com/zief0002/epsy-8252/raw/master/assignments/s21-assignment-05-evidence-and-model-selection.Rmd)
</td>
<td align="center" style="vertical-align:middle;">
[<span class="fas fa-link" style="color: #ff2600; font-size: 20px;"></span>](https://zief0002.github.io/epsy-8252/assignments/s21-assignment-05-evidence-and-model-selection.html)
</td>
</tr>

<tr>
<td>Assignment \#6: *Mixed-Effects Regression Models: Cross-Sectional Analysis*</td>
<td>Apr. 15</td>
<td>Apr. 19</td>
<td align="center" style="vertical-align:middle;">
[<span class="fab fa-markdown" style="color: #ff2600; font-size: 20px;"></span>](https://github.com/zief0002/epsy-8252/raw/master/assignments/s21-assignment-06-lmer-models-cross-sectional.Rmd)
</td>
<td align="center" style="vertical-align:middle;">
[<span class="fas fa-link" style="color: #ff2600; font-size: 20px;"></span>](https://zief0002.github.io/epsy-8252/assignments/s21-assignment-06-lmer-models-cross-sectional.html)
</td>
</tr>

<tr>
<td>Assignment \#7: *Mixed-Effects Regression Models: Longitudinal Analysis*</td>
<td>Apr. 27</td>
<td>Apr. 28</td>
<td align="center" style="vertical-align:middle;">
[<span class="fab fa-markdown" style="color: #ff2600; font-size: 20px;"></span>](https://github.com/zief0002/epsy-8252/raw/master/assignments/s21-assignment-07-lmer-models-longitudinal.Rmd)
</td>
<td align="center" style="vertical-align:middle;">
[<span class="fas fa-link" style="color: #ff2600; font-size: 20px;"></span>](https://zief0002.github.io/epsy-8252/assignments/s21-assignment-07-lmer-models-longitudinal.html)
</td>
</tr>



<tr>
<td>Assignment \#8 *Logistic Regression* **(Optional)**</td>
<td colspan="2" align="center" style="vertical-align:middle;">May 11<br />(due at 12:00pm)</td>
<td align="center" style="vertical-align:middle;">
[<span class="fab fa-markdown" style="color: #ff2600; font-size: 20px;"></span>](https://github.com/zief0002/epsy-8252/raw/master/assignments/s21-assignment-08-logistic-regression.Rmd)
</td>
<td align="center" style="vertical-align:middle;">
[<span class="fas fa-link" style="color: #ff2600; font-size: 20px;"></span>](https://zief0002.github.io/epsy-8252/assignments/s21-assignment-08-logistic-regression.html)
</td>
</tr>


</tbody>
</table>
