# Moving Online





Hello Scholars,

As you probably saw, the University of Minnesota will be [online until at least April 01](https://drive.google.com/file/d/1_ph5nt6DcL1bds0ojWaojg5c6vgacGco/view) to mitigate the risk of exposure to COVID-19. Subsequently, EPsy 8252 will be meeting online starting on Wednesday March 18. I have set up a recurring Zoom link for us to meet at during our regularly scheduled class times. 

<br />

- **Zoom Link:** https://umn.zoom.us/j/8227826925

<br />

Note the link is the same for both classes. If this is your first time using Zoom, you may need to download the Zoom client before you connect. You will also need to login using your x500 information. You can get more information about using Zoom at https://umn.zoom.us/

<br />

The TAs and I will be available during our office hours, but as with classes, they will also be virtual. If you want to meet during regularly scheduled office hours, I am available at the same Zoom link. (I will add links for Mireya and Amani once I have them.)

- **Andy's Office Hours:** https://umn.zoom.us/j/8227826925
- **Mireya's Office Hours:** https://umn-private.zoom.us/j/789377247
- **Amani's Office Hours:** https://umn-private.zoom.us/j/306263530

<br />

If you want to schedule a separate time to meet virtually, please send a Google Calendar invite and enable the video conferencing option (`Add conferencing > Hangouts Meet`). This will create a Google Hangout link in the calendar event that we can connect to.

<br />

I will try to remember to record the lectures (please remind me). I will make these available here:

- https://drive.google.com/drive/folders/1hzp1Sf9VmwpoEDbqqdtmYvyrCO9N4uyN?usp=sharing

<br />

As we make this (hopefully short-term) transition, I expect there to be some bumps along the way. The TAs and I will be flexible as we all sort out the processes and issues that crop up. Please also be flexible with us as we adapt. I encourage you to communicate with us so that we can help in any way we can. Take care of yourselves and your families. The university has several resources available to you, including [mental health resources](http://mentalhealth.umn.edu/).

<br />

Be seeing you in cyberspace soon.

<br />

Andy, Mireya, &amp; Amani




